### ISSUE TITLE
Generated code uses circe-java8 which does not exist on latest Circe version (HTTP4S, Scala 2.13)

### ISSUE THREAD

**Issue by hugo-vrijswijk** [twilio/guardrail#361]
I was trying Guardrail in combination with a Scala 2.13 http4s project, but I ran into an issue. Generated Guardrail code uses circe-java8, which is removed in Circe 0.12.0-M3 (see [release notes](https://github.com/circe/circe/releases/tag/v0.12.0-M3)). This is also the lowest version that supports Scala 2.13. This means that code generated by Guardrail will not compile on any Circe version higher than 0.12.0-M3 as it cannot find the package. 

Current behaviour:

```
[info] Compiling 8 Scala sources to /myFolder/guardrail-http4s-example/target/scala-2.13/classes ...
[error] /myFolder/guardrail-http4s-example/target/scala-2.13/src_managed/main/com/example/quickstart/endpoints/definitions/package.scala:7:17: object java8 is not a member of package io.circe
[error] import io.circe.java8.time._
[error]                 ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

Expected behaviour:

Guardrail does not give compile errors due to generated code that is not compatible with the latest Circe version.

Used versions:
- Guardrail: 0.52.1
- Circe: 0.12.0-M4
- Http4s: 0.21.0-M2

Example project: https://github.com/hugo-vrijswijk/guardrail-http4s-example

I would be interested in helping with a fix, if I can be pointed in the right direction. Perhaps remove the import when the Circe version 0.12.0-M2 or higher?

**Comment by kelnos** [comment]
Hmm, looks like circe-java8 was removed in 0.12.0-M3 (https://github.com/circe/circe/releases/tag/v0.12.0-M3), as they now require java8, and so the circe-java8 stuff has been moved into the core.

I'm not sure what the best approach is here; if we remove the imports, we can only support circe 0.12 (which hasn't even been stably released yet).  If we don't, 0.12+ builds will fail.

It's a shame that the circe folks aren't providing back-compat names to ease the transition.  I don't think we can reasonably force people to use 0.12 if they want to use guardrail.

**Comment by kelnos** [comment]
> Perhaps remove the import when the Circe version 0.12.0-M2 or higher?

Just to follow up on this particular point: aside from potentially declaring a minimum required version, guardrail is version-agnostic and has no idea what versions of dependencies you actually end up using.

**Comment by hugo-vrijswijk** [comment]
I'm playing around a little with a locally published version of Guardrail that has removed the single `io.circe.java8` import (you can see in the above-linked repo in the `master`, `scala-212` & `scala-211` branches). The only situation where compilation errors actually occur without the import seem to be when using scala 2.11. Even when using Circe 0.11 (note: the circe-java8 package was not even needed in my project with 2.12). Perhaps Circe already publishes slightly different artifacts for 2.11 and 2.12 given that 2.12 can only be built with Java 8 or higher?

I am not sure what Guardrail's plans are for supporting 2.11. But perhaps dropping 2.11 support in order to support 2.13 is an option? Or even publishing slightly different code for the different scala versions?

**Comment by kelnos** [comment]
You'll almost certainly get compilation failures without circe-java8 (when using circe 0.11 and below) if you have `type: string` params/props with `format: date` or `format: date-time`.

**Comment by hugo-vrijswijk** [comment]
In the example repo I have a [`.yaml` with both `date` and `date-time`](https://github.com/hugo-vrijswijk/guardrail-http4s-example/blob/scala-212/src/main/resources/api.yaml#L26-L39), no `circe-java8` in the [`build.sbt`](https://github.com/hugo-vrijswijk/guardrail-http4s-example/blob/scala-212/build.sbt#L17). The [implementation uses both](https://github.com/hugo-vrijswijk/guardrail-http4s-example/blob/scala-212/src/main/scala/com/example/quickstart/endpoints/HelloHandlerImpl.scala#L10).

With the released version of Guardrail, the only compile error I get is that the import of `io.circe.java8` can not be found. With the locally published version (which removes the import) there are no compile errors

**Comment by kelnos** [comment]
That's strange.  @blast-hardcheese, any idea what's going on here?  Are we using circe-java8 for something else and I'm just confused?  I thought it was for the date-time en/decoders.

**Comment by blast-hardcheese** [comment]
doesn't work for me
```
[error] /private/tmp/guardrail-http4s-example/target/scala-2.13/src_managed/main/com/example/quickstart/endpoints/definitions/package.scala:7:17: object java8 is not a member of package io.circe
[error] import io.circe.java8.time._
[error]                 ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 52 s, completed Aug 2, 2019 3:08:02 PM
```

**Comment by blast-hardcheese** [comment]
this is for sha `b52640ded8784a8d34756211e54b9936ce4314b4`

**Comment by blast-hardcheese** [comment]
Oh, I missed the "locally released version without the imports", one minute...

**Comment by blast-hardcheese** [comment]
OK! So, it seems as though 0.10.0-M2 and above have had the java8 stuff built-in if you run Scala 2.12 and above. This is why it just works if you're using 2.12.

The path forward here is to add a note in the Scala documentation that if you want 2.11 support with `date`/`date-time`, explicitly add your own `circe-java8` dependency, and in your `build.sbt` add `imports=List("io.circe.java8._")`

Are you available to make this change? If so, removing the explicit java8 shim imports should be totally possible.

Either way, thanks for bringing this up!

**Comment by hugo-vrijswijk** [comment]
Yeah, I would be up for making this change! Is the `imports` sbt task already a thing?
